- name: Документация по Ansible в Azure
  href: ./index.yml
- name: Обзор
  items:
    - name: Общие сведения об Ansible в Azure
      href: ./ansible-overview.md
- name: Краткие руководства
  expanded: true
  items:
    - name: Развертывание шаблона решения Ansible в CentOS
      href: ./ansible-deploy-solution-template.md
    - name: Установка Ansible на виртуальные машины Linux
      href: ./ansible-install-configure.md
      maintainContext: true
    - name: Запуск модулей playbook в Cloud Shell
      href: ./ansible-run-playbook-in-cloudshell.md
    - name: Работа с Виртуальными машинами Linux
      expanded: true
      items:
        - name: Настройка виртуальных машин Linux
          href: ./ansible-create-vm.md
          maintainContext: true
        - name: Управление виртуальными машинами Linux
          href: ./ansible-manage-linux-vm.md
          maintainContext: true
- name: Учебники
  items:
    - name: Шлюз приложений Azure
      items:
        - name: Управление веб-трафиком
          href: ./ansible-create-configure-application-gateway.md
    - name: Служба приложений Azure
      items:
        - name: Настройка приложений
          href: ./ansible-create-configure-azure-web-apps.md
        - name: Масштабирование приложений
          href: ./ansible-scale-azure-web-apps.md
    - name: Azure DevTest Labs
      items:
        - name: Настройка лабораторий
          href: ./ansible-devtest-labs-configure.md
    - name: Служба Azure Kubernetes (AKS)
      items:
        - name: Настройка кластеров AKS
          href: ./ansible-create-configure-aks.md
        - name: Настройка сети Azure CNI
          href: ./ansible-aks-configure-cni-networking.md
        - name: Настройка сети kubenet
          href: ./ansible-aks-configure-kubenet-networking.md
        - name: Настройка ролей RBAC в кластере AKS
          href: ./ansible-aks-configure-rbac.md
    - name: Azure HDInsight
      items:
        - name: Настройка кластеров
          href: ./ansible-azure-hdinsight-configure.md
    - name: Служебная шина Azure
      items:
        - name: Настройка очередей
          href: ./ansible-service-bus-queue-configure.md
        - name: Настройка разделов
          href: ./ansible-service-bus-topic-configure.md
    - name: База данных
      items:
        - name: Настройка Базы данных Azure для MySQL
          href: ./ansible-create-configure-mysql.md
        - name: "Настройка учетных записей Azure Cosmos\_DB"
          href: ./ansible-data-cosmos-configure.md
        - name: Настройка кэша Redis для Azure
          href: ./ansible-data-cache-for-redis-configure.md
    - name: Динамический список
      items:
        - name: Управление ресурсами Azure
          href: ./ansible-manage-azure-dynamic-inventories.md
    - name: Виртуальные машины
      items:
        - name: Создание Общей коллекции образов
          href: ansible-vm-create-from-shared-generalized-image.md
    - name: Масштабируемые наборы виртуальных машин
      items:
        - name: Configure
          href: ./ansible-create-configure-vmss.md
        - name: Развертывание
          href: ./ansible-deploy-app-vmss.md
        - name: Автомасштабирование
          href: ./ansible-auto-scale-vmss.md
        - name: Обновление пользовательского образа
          href: ./ansible-vmss-update-image.md
        - name: Создание Общей коллекции образов
          href: ansible-vm-create-from-shared-generalized-image.md
    - name: Виртуальная сеть
      items:
        - name: Настройка пиринга
          href: ./ansible-vnet-peering-configure.md
        - name: Настройка таблиц маршрутов
          href: ./ansible-create-configure-route-table.md
- name: Примеры
  items:
    - name: Тестовая служба Ansible для Azure
      href: 'https://github.com/microsoft/ansiblelabs'
    - name: Примеры для сборника схем Ansible для Azure
      href: 'https://github.com/Azure-Samples/ansible-playbooks'
- name: Справочник
  items:
    - name: Роли в сборнике схем
      items:
        - name: azure_module
          href: 'https://galaxy.ansible.com/Azure/azure_modules/'
        - name: azure_preview_module
          href: 'https://galaxy.ansible.com/Azure/azure_preview_modules'
    - name: Выпуски и компоненты
      href: ./ansible-matrix.md
    - name: Все модули для Azure
      href: 'https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules#azure'
- name: Ресурсы
  items:
    - name: Расширение Visual Studio Code для Ansible
      href: 'https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible'