- name: Kubernetes в Azure
  href: ./index.yml
- name: Обзор
- name: Краткие руководства
  expanded: true
- name: Учебники
- name: Основные понятия
- name: Практические руководства
  items:
    - name: Сохранение данных в Файлах Azure
      href: ../../aks/azure-files.md?toc=%2fazure%2fcontainer-service%2fkubernetes%2ftoc.json
    - name: Монитор
    - name: Развертывание приложений Spring Boot
      items:
        - name: Развертывание приложения Spring Boot в Linux в Службе контейнеров Azure
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: Развертывание приложения Spring Boot в кластере Kubernetes в Службе контейнеров Azure
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
        - name: Развертывание приложения Spring Boot с помощью подключаемого модуля Maven fabric8
          href: container-service-deploy-spring-boot-app-using-fabric8-maven-plugin.md
- name: Справочник
  items:
    - name: Azure CLI
      href: /cli/azure/acs
    - name: PowerShell
      href: /powershell/module/az.compute
    - name: REST
      href: /rest/api/container-service
- name: Ресурсы
  items:
    - name: Стратегия развития Azure
      href: 'https://azure.microsoft.com/roadmap/'
    - name: "Шаблоны\_— модуль\_ACS"
      href: 'https://github.com/Azure/acs-engine'
    - name: Цены
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: Доступность по регионам
      href: 'https://azure.microsoft.com/regions/services/'
    - name: Stack Overflow
      href: 'https://stackoverflow.com/questions/tagged/azure-container-service'
    - name: Видео
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'