- name: Azure Arc с поддержкой Kubernetes
  href: index.yml
- name: Обзор
  items:
    - name: Сведения об Azure Arc с поддержкой Kubernetes
      href: overview.md
- name: Практические руководства
  items:
    - name: Операции с кластером
      items:
        - name: Подключение кластера
          href: connect-cluster.md
        - name: Использование GitOps для подключенных кластеров
          href: use-gitops-connected-cluster.md
        - name: Использование GitOps с Helm
          href: use-gitops-with-helm.md
        - name: Принудительное применение GitOps с помощью службы "Политика Azure"
          href: use-azure-policy.md
        - name: Azure Monitor для контейнеров
          href: deploy-azure-monitor-for-containers.md
        - name: Применение политик управления допуском с помощью службы "Политика Azure"
          href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.json
        - name: Развертывание рабочих нагрузок для Интернета вещей
          href: deploy-azure-iot-edge-workloads.md
        - name: Подключение субъекта-службы
          href: create-onboarding-service-principal.md
        - name: Устранение неполадок
          href: Troubleshooting.md